# Rifle's Chair plugin by Rifle D. Luffy
# Version 6.0
# #=============[Seat Configuration]=============##
# stair-seating-position: The exact positions of where the armorstand spawns on a stair; default 0.35,0.3,0.5
# slab-seating-position: The exact positions of where the armorstand spawns on a slab; default 0.5,0.3,0.5
# carpet-seating-position: The exact positions of where the armorstand spawns on a carpet; default 0.5,-0.15,0.5
# be careful when playing around with this feature!
# in the format x,y,z where...
# x is forward
# y is up
# z is sideways (positive z is to the right, negative z is the left)
#
# exit-seat-where-facing: Exit the seat where you are facing.
# max-distance: the maximum distance a player can be in order to sit on the seat
# max-item-count-to-sit: If they have more than this, they can't sit. Example: >10 dirt cannot sit
# set it to -1 to cancel.
# require-signs-at-end: checks for signs at the end of a seat; false by default
# priority-on-if-has-perm: if they have the perm rfchairs.priority, they will be allowed to replace users
# allow-trap-door-chairs: allows the player to sit on a chair that resembles a "throne"
# require-empty-hand: players must have no items in their hand to sit
# #=============[When Damaged By an Entity]=============##
# eject-player-on-damage: Should it eject players of their seats when damaged?
# minimum-eject-damage: The minumum damage needed to toss a player out of their seat
# face-attacker-when-ejected: Should the attacked face the attacker when hit out of their seat?
# #=============[Tossing players out of seats]=============##
# toss-player: will the players be tossed when they 
# toss-velocity: the velocity of the attacked when knocked out of their seat
# scale-toss-velocity: whether or not the toss-velocity will increase if attacker is running
# velocity-scale-factor: how much the velocity is multiplied if attacker is running
# #=============[Customization]=============##
# regen-when-sitting: players regenerate when sitting on chairs
# regen-potency: the regen potion effect level where 0 is level 1
# allow-custom-messages: allow the use of custom messages when events are triggered
# allowed-chairs: The chairs that people are allowed to sit on
stair-seating-position: 0.5,0.3,0.5
slab-seating-positiong: 0.5,0.3,0.5
carpet-seating-position: 0.5,-0.15,0.5
disable-update-message-if-on-latest: false
disable-update-messages: false
exit-seat-where-facing: false
allow-trap-door-chairs: true
require-empty-hand: false
max-distance: 2
max-item-count-to-sit: -1
require-signs-at-end: false
eject-player-on-damage: false
minimum-eject-damage: 2
face-attacker-when-ejected: false
toss-player: false
toss-velocity: 0.5
scale-toss-velocity: true
velocity-scale-factor: 2
regen-when-sitting: true
regen-potency: 0
allow-custom-messages: false
priority-on-if-has-perm: true
allowed-chairs:
  - STAIRS*
  - SLAB*
  - CARPET*
blacklisted-chairs: []
disabled-worlds: []